config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :students do
    resources :addresses
  end
  
  resources :courses, only: [:show]

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :student
  validates_presence_of :description, :street, :city, :state, :zipcode
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates_presence_of :title
  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
  validates_presence_of :name
  has_many :addresses
  has_many :student_courses
  has_many :courses, through: :student_courses
  
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def new
    @student = Student.find(params[:student_id])
    @address = Address.new
  end

  def create
    @student = Student.find(params[:student_id])
    @address = @student.addresses.create(address_params)
    if @address.save
      redirect_to student_path(@student)
    else
      render :new
    end
  end

  private
  def address_params
    params.require(:address).permit(:description, :street, :city, :state, :zipcode)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def show
    @course = Course.includes(:students).find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end
  
  def show
    @student = Student.includes(:courses, :addresses).find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.create(student_params)
    if @student.save
      redirect_to student_path(@student)
    else
      render :new
    end
  end

    def edit
      @student = Student.find(params[:id])
    end

    def update
      @student = Student.find(params[:id])
      @student.update(student_params)
      if @student.save
        redirect_to student_path(@student)
      else
        render :edit
      end
    end

    def destroy
      student = Student.find(params[:id])
      student.destroy

      redirect_to students_path
    end

  private
  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_form.html.erb
<%= form_for [@student, @address] do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :street %>
  <%= f.text_field :street %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.text_field :state %>

  <%= f.label :zipcode %>
  <%= f.text_field :zipcode %>

  <%= f.submit %>
<% end %>

app/views/addresses/new.html.erb
<!doctype html>
<html lang="en">
<head>
  <h2>Create a New Address!</h2>
</head>

<body>
  <%= render partial: 'form' %>
</body>
</html>

app/views/courses/show.html.erb
<!doctype html>
<html lang="en">
<head>
  <h2>Course: <%= @course.title %></h2>
</head>

<body>
  <h4>Student Enrolled:</h4>
  <ul>
  <% @course.students.each do |student| %>
    <li>
      <%= student.name %>
    </li>
  <% end %>
  </ul>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enrollment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to 'All Students', students_path %>
      <%= link_to 'Create a Student', new_student_path %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/students/edit.html.erb
<!doctype html>
<html lang="en">
<head>
  <h2>Edit a Student!</h2>
</head>

<body>
  <%= render partial: 'form' %>
</body>
</html>

app/views/students/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <h2>All Students</h2>
</head>

<body>
  <ul>
  <% @students.each do |student| %>
    <li class="student_<%= student.name %>">
      <%= link_to student.name, student_path(student) %>
      <%= link_to 'Delete', student_path(student), method: 'delete' %>
    </li>
  <% end %>
  </ul>
</body>
</html>

app/views/students/new.html.erb
<!doctype html>
<html lang="en">
<head>
  <h2>Create a New Student!</h2>
</head>

<body>
  <%= render partial: 'form' %>
</body>
</html>

app/views/students/show.html.erb
<!doctype html>
<html lang="en">
<head>
  <h2>Student: <%= @student.name %></h2>
</head>

<body>
  <h4>Student Courses:</h4>
  <ul>
  <% @student.courses.each do |course| %>
    <li>
      <%= course.title %>
    </li>
  <% end %>
  </ul>
  <h4>Student Addresses:</h4>
  <ul>
  <% @student.addresses.each do |address| %>
    <li>
      <%= address.description %>
      <%= address.street %>
      <%= address.city %>
      <%= address.state %>
      <%= address.zipcode %>
    </li>
  <% end %>
  </ul>
</body>
</html>